### ISSUE TITLE
Set custom bake range?

### ISSUE THREAD

**Issue by Entropy159** [u3dreal/molecular-plus#27]
It would be really nice if I could set a custom range to bake without changing the render range. My particles don't spawn in until almost frame 300, but I am forced to bake all the empty frames before that.

**Comment by u3dreal** [comment]
Unborn particles are not processed ..

**Comment by Entropy159** [comment]
Yeah, it definitely bakes faster when there aren't particles, but I would like to be able to skip it entirely. I have 25 substeps, meaning I have to wait 7800 frames before I can see the actual simulation. Then sometimes I have to stop it, change a few settings, and start baking all over again, waiting 7800 frames to see if it works.

**Comment by VarnaScelestus** [comment]
Seconding this. Despite not running any heavy calculations since there aren't any particles born on the frames before the particle system takes effect, it still wastes a LOT of time going through the frames prior. In my use case, I have to wait for 80% of the expanded timeline before it gets to my simulation, which actually ends up taking more time than the simulation itself!

**Comment by u3dreal** [comment]
That is not so easy since the sim is set up at frame 1 ...  have to think about a solution here ..
consider donating so i have time for that.

**Comment by u3dreal** [comment]
After some digging i found this was broken .. it should work now along with resuming from an existing cache if you want to give it a try 
https://github.com/u3dreal/molecular-plus/actions/runs/6791787028

Unzip once and install

**Comment by u3dreal** [comment]
fixed
